### ISSUE TITLE
Thanks for making this.

### ISSUE THREAD

**Issue by rams3sh** [olirice/cachetools_ext#1]
Hey Oliver 

Thanks for making this extension as I was really in search of SQLITE based cache for [my small project](https://github.com/rams3sh/botocache). I had used your SQLITE cache code from [here](https://github.com/olirice/cachetools_ext/blob/develop/cachetools_ext/sqlite.py) and I wanted to give credit to you in the project README. 

I had mentioned your name  under CREDITS section as of now and I wanted to know if that's okay with you . 

Thanks again !!

**Comment by olirice** [comment]
For sure! You're welcome to use any thing in this repo.

Just want to make sure you realize that the sqlite cache class was removed from this lib several months ago. I ran into problems with the database getting blocked/locked when multiple workers attempted to access large binary objects in the same cache database.

It should be fine for single threaded access (afaik) but its definitely not perfect
